name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: clippy, rustfmt

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Check formatting
        run: cargo fmt  -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -Dclippy::all

      - name: Build
        run: cargo build --all --release

      - name: Name Release
        if: startsWith(github.ref, 'refs/tags/')
        id: name_release
        run: echo ::set-output name=RELEASE::etl-extract-${GITHUB_REF/refs\/tags\//}-x86-64-linux

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NAME: ${{ steps.name_release.outputs.RELEASE }}
        run: |
          tar -zcvf $NAME.tar.gz -C target/release etl-extract
          sha256sum -b --tag $NAME.tar.gz > $NAME.checksum

      - name: Push Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.name_release.outputs.RELEASE }}.tar.gz
            ${{ steps.name_release.outputs.RELEASE }}.checksum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
